name: Release

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    name: Build & Upload to Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/mmwave-card.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}